name: Deploy site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Setup Node 🧰
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install JS deps 📦
        run: npm ci
      - name: Install and Build 🔧
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          export JEKYLL_ENV=production
          bundle exec jekyll build
      - name: Purge unused CSS 🧹
        run: npx purgecss -c purgecss.config.js
      - name: Upload built site ⬆️
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
          retention-days: 14
      - name: Install browser 🌐
        if: github.event_name == 'pull_request'
        run: npx playwright install --with-deps chromium
      - name: Browser tests 🧪
        if: github.event_name == 'pull_request'
        run: npm test
      - name: Deploy 🚀
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
